name: tensorflow-3.5
channels:
  - defaults
dependencies:
  - alabaster=0.7.10=py35h6fb19ab_0
  - asn1crypto=0.24.0=py35_0
  - babel=2.5.3=py35_0
  - backcall=0.1.0=py35_0
  - bleach=2.1.3=py35_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py35_0
  - cffi=1.11.5=py35h9745a5d_0
  - chardet=3.0.4=py35hb6e9ddf_1
  - cryptography=2.2.2=py35h14c3975_0
  - cycler=0.10.0=py35hc4d5149_0
  - dbus=1.13.2=hc3f9b76_0
  - decorator=4.3.0=py35_0
  - docutils=0.14=py35hd11081d_0
  - entrypoints=0.2.3=py35h48174a2_2
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - glib=2.53.6=h5d9569c_2
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.12.4=h33fb286_0
  - gstreamer=1.12.4=hb53b477_0
  - h5py=2.7.1=py35h8d53cdc_0
  - hdf5=1.10.1=h9caa474_1
  - html5lib=1.0.1=py35h2f9c1c0_0
  - icu=58.2=h9c2bf20_1
  - idna=2.6=py35h8605a33_1
  - imagesize=1.0.0=py35_0
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py35_0
  - ipython=6.3.1=py35_0
  - ipython_genutils=0.2.0=py35hc9e07d0_0
  - ipywidgets=7.2.1=py35_0
  - jedi=0.11.1=py35_1
  - jinja2=2.10=py35h480ab6d_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py35h4395190_0
  - jupyter=1.0.0=py35_4
  - jupyter_client=5.2.3=py35_0
  - jupyter_console=5.2.0=py35h4044a63_1
  - jupyter_core=4.4.0=py35ha89e94b_0
  - kiwisolver=1.0.1=py35hcb1117a_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.34=hb9fc6fc_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=h28f6b97_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=hf84eae3_0
  - markupsafe=1.0=py35h4f4fcf6_1
  - matplotlib=2.2.2=py35h0e671d2_1
  - mistune=0.8.3=py35_0
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py35h3010b51_0
  - mkl_random=1.0.1=py35h629b387_0
  - nbconvert=5.3.1=py35hc5194e3_0
  - nbformat=4.4.0=py35h12e6e07_0
  - ncurses=6.0=h9df7e31_2
  - nltk=3.2.5=py35h09ad193_0
  - notebook=5.4.1=py35_0
  - numpy=1.14.2=py35hdbf6ddf_1
  - numpydoc=0.8.0=py35_0
  - olefile=0.45.1=py35_0
  - openssl=1.0.2o=h20670df_0
  - packaging=17.1=py35_0
  - pandas=0.22.0=py35hf484d3e_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py35h1565a15_1
  - parso=0.1.1=py35h1b200a3_0
  - pcre=8.42=h439df22_0
  - pexpect=4.5.0=py35_0
  - pickleshare=0.7.4=py35hd57304d_0
  - pillow=5.1.0=py35h3deb7b8_0
  - pip=9.0.3=py35_0
  - prompt_toolkit=1.0.15=py35hc09de7a_0
  - ptyprocess=0.5.2=py35h38ce0a3_0
  - pycparser=2.18=py35h61b3040_1
  - pygments=2.2.0=py35h0f41973_0
  - pyopenssl=17.5.0=py35h4f8b8c8_0
  - pyparsing=2.2.0=py35h041ed72_1
  - pyqt=5.9.2=py35h751905a_0
  - pysocks=1.6.8=py35_0
  - python=3.5.5=hc3d631a_1
  - python-dateutil=2.7.2=py35_0
  - pytz=2018.4=py35_0
  - pyzmq=17.0.0=py35h14c3975_0
  - qt=5.9.4=h4e5bff0_0
  - qtconsole=4.3.1=py35h4626a06_0
  - readline=7.0=ha6073c6_4
  - requests=2.18.4=py35hb9e6ad1_1
  - scikit-learn=0.19.1=py35hbf1f462_0
  - scipy=1.0.1=py35hfc37229_0
  - send2trash=1.5.0=py35_0
  - setuptools=39.0.1=py35_0
  - simplegeneric=0.8.1=py35_2
  - sip=4.19.8=py35hf484d3e_0
  - six=1.11.0=py35h423b573_1
  - snowballstemmer=1.2.1=py35h5435977_0
  - sphinx=1.7.2=py35_0
  - sphinxcontrib=1.0=py35hcb7efd2_1
  - sphinxcontrib-websupport=1.0.1=py35h3537809_1
  - sqlite=3.22.0=h1bed415_0
  - terminado=0.8.1=py35_1
  - testpath=0.3.1=py35had42eaf_0
  - tk=8.6.7=hc745277_3
  - tornado=5.0.1=py35_1
  - traitlets=4.3.2=py35ha522a97_0
  - typing=3.6.4=py35_0
  - urllib3=1.22=py35h2ab6e29_0
  - wcwidth=0.1.7=py35hcd08066_0
  - webencodings=0.5.1=py35hb6cf162_1
  - wheel=0.31.0=py35_0
  - widgetsnbextension=3.2.0=py35_0
  - xz=5.2.3=h55aa19d_2
  - zeromq=4.2.5=h439df22_0
  - zlib=1.2.11=ha838bed_2
  - pip:
    - absl-py==0.1.13
    - astor==0.6.2
    - gast==0.2.0
    - grpcio==1.11.0
    - keras==2.1.5
    - markdown==2.6.11
    - progressbar2==3.37.1
    - protobuf==3.5.2.post1
    - python-utils==2.3.0
    - pyyaml==3.12
    - tensorboard==1.7.0
    - tensorflow-gpu==1.7.0
    - termcolor==1.1.0
    - werkzeug==0.14.1
prefix: /home/ubuntu/anaconda3/envs/tensorflow-3.5

